config/routes.rb
Rails.application.routes.draw do
  # devise_for を使ってデバイスを設定
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  # 検索のためのルーティング
  get 'search/index'

  # public スコープ内のルーティング定義
  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"

    get '/customers/my_page', to: 'customers#show'

    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'

    # 検索
    get 'search', to: 'search#index', as: :search

    # 商品のルーティング
    resources :items, only: [:index, :show]

    # 顧客に関するルーティング
    resource :customers do
      get 'unsubscribe' # 退会ページへのルーティング
      patch 'withdraw' # 退会処理のルーティング

      collection do
        get :my_page
      end
    end

    # カートに関するルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end

    # 注文に関するルーティング
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
        get :thanks
      end
    end

    # 住所に関するルーティング
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    # ジャンルに関するルーティング
    resources :genres, only: [:show]
  end

  # admin スコープ内のルーティング
  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    customers = Customer.all
    @customers = customers.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)  #, notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
      :post_code, :address, :telephone_number, :email, :is_active )
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h3><%= @customer.last_name %><%= @customer.first_name %></h3>
    <h4>さんの</h4>
    <h3>会員情報編集</h3>
  </div>
  <div class="row mt-3">
    <%= form_with model: @customer, url: admin_customer_path(@customer),method: :patch, local: true do |f| %>
      <div class="row">
        <div class="col-5">会員ID</div>
        <div class="col-3"><%= @customer.id %></div>
      </div>
      
      <div class="row mt-2">
        <div class="col-4">氏名</div>
        <div class="col-4"><%= f.text_field :last_name, autofocus: true, class: "form-control" %></div>
        <div class="col-4"><%= f.text_field :first_name, class: "form-control"  %></div>
      </div>
            
      <div class="row mt-2">
        <div class="col-4">フリガナ</div>
        <div class="col-4"><%= f.text_field :last_name_kana, pattern: "[ァ-ヶー－]+",class: "form-control" %></div>
        <div class="col-4"><%= f.text_field :first_name_kana, pattern: "[ァ-ヶー－]+",class: "form-control" %></div>
      </div>
          
      <div class="row mt-2">
        <div class="col-4">郵便番号</div>
        <div class="col-4"><%= f.text_field :post_code, pattern: '\d{3}\d{4}',class: "form-control" %></div>  
      </div>
          
      <div class="row mt-2">
        <div class="col-4">住所</div>
        <div class="col-8"><%= f.text_field :address, pattern: '^[\p{Han}\w\s]+$',class: "form-control" %></div>
      </div>
          
      <div class="row mt-2">
        <div class="col-4">電話番号</div>
        <div class="col-4"><%= f.text_field :telephone_number, pattern: '\d{10,11}',class: "form-control" %></div>
      </div>
              
      <div class="row mt-2">
        <div class="col-4">メールアドレス</div>
        <div class="col-4"><%= f.email_field :email,class: "form-control" %></div>  
      </div>
        
      <div class="row mt-2">
        <div class="col-4">会員ステータス</div>
        <div class="col-4">
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, "有効" %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, "退会" %>
        </div>
      </div>
        
      <div class="actions text-center">
        <div class="row mt-4">
          <div class="col-3 offset-4"><%= f.submit "変更を保存", class: "btn btn-lg btn-success" %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">

  <div class="row mt-3">
    <div class="text-bg-light offset-2">会員一覧</div>
  </div>

  <div class="row justify-content-center">
    <table class='col-10 table table-hover table-inverse'>
      <thead>
        <tr  class="table-active">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %><%=customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <div class="col-sm-12">
                <% if customer.is_active %>
                  <p class="text-success"><strong>有効</strong></p>
                <% else %>
                  <p class="text-secondary"><strong>退会</strong></p>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @customers %>
  </div>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-3">
    <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
  </div>

  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">会員ID</div>
    <div class="col-6"><%= @customer.id %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">氏名</div>
    <div class="col-6"><%= @customer.last_name %>&emsp;<%= @customer.first_name %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">フリガナ</div>
    <div class="col-6"><%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">郵便番号</div>
    <div class="col-6"><%= @customer.post_code.gsub("-","") %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">住所</div>
    <div class="col-6"><%= @customer.address %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">電話番号</div>
    <div class="col-6"><%= @customer.telephone_number %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">メールアドレス</div>
    <div class="col-6"><%= @customer.email %></div>
  </div>
  <div class="row justify-content-center form-group mt-3 ">
    <div class="col-3">会員ステータス</div>
    <div class="col-6">
      <% if @customer.is_active %>
        <p class="text-success"><strong>有効</strong></p>
      <% else %>
        <p class="text-secondary"><strong>退会</strong></p>
      <% end %>
    </div>
  </div>
    <div class="row justify-content-center form-group mt-3 ">
    <div class="col-2 offset-3">
      <%= link_to "編集する", edit_admin_customer_path(params[:id]), class: "btn btn-success" %>
    </div>
    <div class="col offset-2">
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>