config/routes.rb
Rails.application.routes.draw do
  # devise_for を使ってデバイスを設定
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  # 検索のためのルーティング
  get 'search/index'

  # public スコープ内のルーティング定義
  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"

    get '/customers/my_page', to: 'customers#show'

    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'

    # 検索
    get 'search', to: 'search#index', as: :search

    # 商品のルーティング
    resources :items, only: [:index, :show]

    # 顧客に関するルーティング
    resource :customers do
      get 'unsubscribe' # 退会ページへのルーティング
      patch 'withdraw' # 退会処理のルーティング

      collection do
        get :my_page
      end
    end

    # カートに関するルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end

    # 注文に関するルーティング
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
        get :thanks
      end
    end

    # 住所に関するルーティング
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    # ジャンルに関するルーティング
    resources :genres, only: [:show]
  end

  # admin スコープ内のルーティング
  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { deposit_pending: 0, payment_confirmed: 1, in_making: 2, preparing_shipment: 3, shipped: 4 }
  
  
  validates :customer_id, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  
  
  def normalize_post_code
    self.post_code = self.post_code.tr("０-９ａ-ｚＡ-Ｚ（）－−", "0-9a-zA-Z()-")
  end
  
  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)

    # Check if the order status is changed to "payment_confirmed"
    if @order.status == "payment_confirmed"
      # Update all order details making status to "pending"
      @order_details.update_all(making_status: :pending)
    end

    redirect_to admin_order_path(@order)  
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h2>注文履歴詳細</h2>


      <div class="row">
        <div class="col-md-7">
          <table class="table">
            <tbody>
              <tr>
                <th>購入者</th>
                <td>
                  <%= link_to admin_customer_path(@order.customer) do %>
                    <%= @order.customer.last_name %>
                    <%= @order.customer.first_name %>
                  <% end %>
                </td>
              </tr>

              <tr>
                <th>配送先</th>
                <td><%= @order.address %></td>
              </tr>

              <tr>
                <th>支払方法</th>
                <td><%= @order.payment_method_i18n %></td>
              </tr>

              <tr>
                <th>注文ステータス</th>
                <td>
                  <%= form_for(@order, url: admin_order_path(@order)) do |f| %>
                    <%= f.select :status, Order.statuses_i18n.invert %>
                    <%= f.submit "更新", class: "btn btn-success" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          <br>
            <table class="table">
              <thead>
                <tr>
                  <th>商品名</th>
                  <th>単価（税込）</th>
                  <th>数量</th>
                  <th>小計</th>
                  <th colspan="2">製作ステータス</th>
                </tr>
              </thead>
            <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= number_to_currency(order_detail.price) %></td>
        <td><%= order_detail.amount %></td>
        <td><%= number_to_currency(order_detail.price * order_detail.amount) %></td>
        <td colspan="2">
          <%= form_for(order_detail, url: admin_order_detail_path(order_detail)) do |f|  %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
            <%= f.submit '更新', class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
        </div>

        <div class="col-md-5">
          <table class="table">
            <tbody>
              <tr>
                <td>商品合計</td>
                <td><%= number_to_currency(@order.total_payment - @order.shipping_cost) %></td>
              </tr>

              <tr>
                <td>送料</td>
                <td><%= number_to_currency(@order.shipping_cost) %></td>
              </tr>

              <tr>
                <td>請求合計金額</td>
                <td><%= number_to_currency(@order.total_payment) %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>