config/routes.rb
Rails.application.routes.draw do
  # devise_for を使ってデバイスを設定
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  # 検索のためのルーティング
  get 'search/index'

  # public スコープ内のルーティング定義
  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"

    get '/customers/my_page', to: 'customers#show'

    get '/customers/information/edit', to: 'customers#edit'
    patch '/customers/information', to: 'customers#update'

    # 検索
    get 'search', to: 'search#index', as: :search

    # 商品のルーティング
    resources :items, only: [:index, :show]

    # 顧客に関するルーティング
    resource :customers do
      get 'unsubscribe' # 退会ページへのルーティング
      patch 'withdraw' # 退会処理のルーティング

      collection do
        get :my_page
      end
    end

    # カートに関するルーティング
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end

    # 注文に関するルーティング
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confirm
        get :thanks
      end
    end

    # 住所に関するルーティング
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    # ジャンルに関するルーティング
    resources :genres, only: [:show]
  end

  # admin スコープ内のルーティング
  namespace :admin do
    get '/' => 'homes#top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update, :index]
    resources :order_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  before_save :normalize_post_code


  belongs_to :customer

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :post_code, presence: true

  def normalize_post_code
      self.post_code = self.post_code.tr("０-９ａ-ｚＡ-Ｚ（）－−", "0-9a-zA-Z  ()-")
  end

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  scope :latest, -> { order(created_at: :desc) }

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item


  def subtotal
    # (cart_item.item.price).floor * amount
    item.with_tax_price * amount  #order/confirmで使用。
  end

  def taxtotal
    (item.price*1.1).floor
  end

  def update_amount(new_amount)
    update(amount: new_amount)
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  #商品説明欄で、半角で入力された数字や記号を半角に変換する処理
  before_save :normalize_introduction

  def normalize_introduction
    self.introduction = self.introduction.tr("０-９ －", "0-9 -")
  end

  #before_save :normalize_post_code

  #def normalize_post_code
    #self.post_code = self.post_code.tr("０-９ －", "0-9 -")
  #end
  #商品編集後保存が出来なかった為、修正しました。
  
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [180, 120]).processed
  end

  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: {in: [true, false]}

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { deposit_pending: 0, payment_confirmed: 1, in_making: 2, preparing_shipment: 3, shipped: 4 }
  
  
  validates :customer_id, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  validates :status, presence: true
  
  
  def normalize_post_code
    self.post_code = self.post_code.tr("０-９ａ-ｚＡ-Ｚ（）－−", "0-9a-zA-Z()-")
  end
  
  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  validates :order_id, presence: true
  validates :item_id, presence: true
  validates :price, presence: true
  validates :amount, presence: true
  validates :making_status, presence: true
  
  enum making_status: { not_started: 0, pending: 1, in_progress: 2, completed: 3, }
  
  def subtotal
    item.with_tax_price * amount  #order/showで使用。
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    items = Item.all
    @items = items.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  # createとupdateで使うストロングパラメータです。
  def item_params

    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price, :is_active)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_customer!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    else
      root_path
    end
  end

  def after_sign_up_path_for(resource)
    my_page_customers_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :telephone_number] )
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_admin_header.html.erb
<li class="mr-4 list-unstyled">
  <%= link_to admin_items_path, class: "btn btn-outline-secondary" do %>
    商品一覧
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to admin_customers_path, class: "btn btn-outline-secondary" do %>
    会員一覧
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to admin_path, class: "btn btn-outline-secondary"  do %>
    注文履歴一覧
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to admin_genres_path, class: "btn btn-outline-secondary" do %>
    ジャンル一覧
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" do %>
    ログアウト
  <% end %>
</li>

app/views/layouts/_publicheader.html.erb
<li class="mr-4 mt-2">
  <%= link_to my_page_customers_path, class: "btn btn-outline-secondary" do %>
    マイページ
  <% end %>
</li>
<li class="mr-4 mt-2">
  <%= link_to items_path, class: "btn btn-outline-secondary" do %>
    商品一覧
  <% end %>
</li>
<li class="mr-4 mt-2">
  <%= link_to cart_items_path, class: "btn btn-outline-secondary" do %>
    カート
  <% end %>
</li>
<li class="mr-4 mt-2">
  <%= link_to destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary" do %>
    ログアウト
  <% end %>
</li>

app/views/layouts/_publicheader_guest.html.erb
<li class="mr-4 mb-4 list-unstyled">
  <%= link_to about_path, class: "btn btn-outline-secondary" do %>
    About
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to items_path, class: "btn btn-outline-secondary" do %>
    商品一覧
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to new_customer_registration_path, class: "btn btn-outline-secondary" do %>
    新規登録
  <% end %>
</li>
<li class="mr-4 list-unstyled">
  <%= link_to new_customer_session_path, class: "btn btn-outline-secondary" do %>
    ログイン
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/0edaaf4d35.js" crossorigin="anonymous"></script>
    <!--各自のフォントURLを設定してください -->
  </head>

  <body>
    <header>
      <div class="container border-bottom">
        <div class="row">
          <div class="mx-5">
            <% if admin_signed_in? %>
              <%= image_tag("icon.jpg", size: "100x100", class: "icon-image") %>
            <% elsif customer_signed_in? %>
              <%= link_to root_path do %>
                <%= image_tag("icon.jpg", size: "100x100", class: "icon-image") %>
              <% end %>
            <% else %>
              <%= link_to root_path do %>
                <%= image_tag("icon.jpg", size: "100x100", class: "icon-image") %>
              <% end %>
            <% end %>
          </div>
          <div class="col">
          <% if customer_signed_in? %>
            <div class="col mt-4 pt-3 text-center">
              <p>ようこそ、<%= current_customer.last_name %>さん！</p>
            </div>
          <% else %>
          <% end %>
          </div>

          <div class="mt-4">
            <ul class="d-flex list-unstyled justify-content-end">
              <% if admin_signed_in? %>
                <%= render 'layouts/admin_header' %>
              <% elsif customer_signed_in? %>
                <%= render 'layouts/publicheader' %>
              <% else %>
                <%= render 'layouts/publicheader_guest' %>
              <% end %>
            </ul>
</div>
        </div>
<!--追加　-->
          <div class="ml-auto mb-2 d-flex justify-content-end">
            <%= form_with url: search_path, method: :get, local: true, class: 'form-inline' do %>
              <div class="input-group">
                <%= text_field_tag :query, params[:query], placeholder: 'Search', class: 'form-control' %>
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary" type="submit">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            <% end %>
          </div>
<!--ここまで　-->
      </div>
    </header>

    <main>
    <%= yield %>


    <div style="height: 190px;"></div>
    </main>

    <footer class="fixed-bottom", style="background-color: white;">

      <div class="container my-3 border-top text-center ">
        <div class="py-5">
        <h3 style="font-family: Monotype Corsiva; color: gray;">Nagano  Cake</h3>
        </div>
      </div>
    </footer>




  </body>
</html>